# Custom Case
_base_dataset: &base_dataset
  case_type: PerformanceCustomDataset
  custom_case_name: FASHION512D200K
  custom_case_description: FASHION512D200K benchmark (512D, 200K vectors)
  custom_dataset_name: FASHION512D200K
  custom_dataset_dir: ""
  custom_dataset_size: 200000
  custom_dataset_dim: 512
  custom_dataset_file_count: 1
  custom_dataset_use_shuffled: false
  custom_dataset_with_gt: true
  k: 10

# envector server settings
_base_envector: &base_envector
  uri: localhost:50050
  eval_mode: mm
  drop_old: true
  load: true

# FLAT
envectorflat:
  <<: [*base_dataset, *base_envector]
  index_name: fashion_flat
  db_label: FASHION512D200K-FLAT

# IVF-FLAT with trained k-means centroids
envectorivfflat:
  <<: [*base_dataset, *base_envector]
  index_name: fashion_ivfflat
  db_label: FASHION512D200K-IVFFLAT
  nlist: 128
  nprobe: 6
  train_centroids: true
  centroids_path: fashion/centroids/centroids_128.npy

# GAS: enVector-customized ANN
envectorivfgas:
  <<: [*base_dataset, *base_envector]
  index_name: fashion_ivfgas
  db_label: FASHION512D200K-IVFGAS
  nlist: 32768
  nprobe: 6
  train_centroids: true
  centroids_path: centroids/clip-vit-b-32/centroids.npy