# Custom Case
_base_dataset: &base_dataset
  case_type: PerformanceCustomDataset
  custom_case_name: PUBMED768D400K
  custom_case_description: PUBMED768D400K benchmark (768D, 400K vectors)
  custom_dataset_name: PUBMED768D400K
  custom_dataset_dir: ""
  custom_dataset_size: 400335
  custom_dataset_dim: 768
  custom_dataset_file_count: 1
  custom_dataset_use_shuffled: false
  custom_dataset_with_gt: true
  k: 10

# envector server settings
_base_envector: &base_envector
  uri: localhost:50050
  eval_mode: mm
  drop_old: true
  load: true

# FLAT
envectorflat:
  <<: [*base_dataset, *base_envector]
  index_name: pubmed_flat
  db_label: PUBMED768D400K-FLAT

# IVF-FLAT with trained k-means centroids
envectorivfflat:
  <<: [*base_dataset, *base_envector]
  index_name: pubmed_ivfflat
  db_label: PUBMED768D400K-IVFFLAT
  nlist: 128
  nprobe: 6
  train_centroids: true
  centroids_path: pubmed/centroids/centroids_128.npy

# GAS: enVector-customized ANN
envectorivfgas:
  <<: [*base_dataset, *base_envector]
  index_name: pubmed_ivfgas
  db_label: PUBMED768D400K-IVFGAS
  nlist: 1024
  nprobe: 6
  train_centroids: true
  centroids_path: centroids/embeddinggemma-300m/centroids.npy